apiVersion: v1
kind: Service
metadata:
  name: {{ include "payload-logger.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "payload-logger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "payload-logger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}